package edu.umkc.csee5110;

public enum MessageType {
	
	REQUESTNAME,
	NAMEACCEPTED,
	SEND_MESSAGE,
	RECEIVE_MESSAGE,
	ADD_NAME,
	REMOVE_NAME,
	PRIVATE_CHAT_INITIATE,
	PRIVATE_CHAT_SEND,
	PRIVATE_CHAT_RECEIVE,
	FILE_INITIATE,
	FILE_REQUEST,
	FILE_OKAY,
	FILE_SEND,
	FILE_RECEIVE,
	NEWNAME;

}
